name: Update gem conservative

on:
  push:
    branches:
      - 'gem/update/**'

permissions:
  contents: write

jobs:
  bundle_update:
    runs-on: ubuntu-latest
    if: ${{ github.event.pusher.name != 'bla' }}
    steps:
      - name: debug
        run: |
          echo '${{ toJSON(github) }}'
          echo '${{ toJSON(github.event.pusher.name) }}'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set GEMNAME
        run: echo "GEMNAME=$(git show -s --format=%s | awk '{print $2}')" >> $GITHUB_ENV # Grabs second word (gemname) from the commit message formatted `Bump gemname from X to Y`
      - name: Configure Git
        run: |
          git config --local user.email 'alexander.dervish@gmail.com'
          git config --local user.name 'Olexandr Dervish'
      - name: Reset last commit
        run: git reset --hard HEAD~1
      - name: Reset remote branch
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - uses: ruby/setup-ruby@v1
        with:
          rubygems: latest
      - name: Update gem
        run: bundle update $GEMNAME --conservative
      - name: Commit
        run: |
          git add Gemfile Gemfile.lock
          git commit -m "Bump $GEMNAME conservative"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
